version: '3.6'
services:

  # Small image that fetches the git repositories we need into a shared volume, then exits
  files:
    image: alpine/git
    entrypoint: /fetch_sources.sh
    volumes:
      - files:/git/sources
      - ./config/fetch_sources.sh:/fetch_sources.sh

  # Node-only services. Ports listen on 2304 internally, and are remapped for nginx
  blog:
    image: fishnet/blog:latest
    working_dir: /app
    networks:
      - appnet
    volumes:
      - ./data/blog/config.js:/app/server/config.js
      - ./data/blog/uploads/:/app/static/uploads/

  # Memes simply builds the css and js, then exits
  # This needs to listen as well.
  memes:
    image: fishnet/memes:latest
    networks:
      - appnet

  # PHP services
  click:
    image: fishnet/click:latest
    working_dir: /var/www
    volumes:
      - ./config/click/php.ini:/usr/local/etc/php/conf.d/settings.ini
    env_file:
      - ./.env
    environment:
      DB_DATABASE: click
    networks:
      - appnet
    depends_on:
      - db

  danger:
    image: fishnet/danger:latest
    working_dir: /var/www
    env_file:
      - ./.env
    networks:
      - appnet
    environment:
      DB_DATABASE: danger
      SITE_URL: $DANGER_URL
    depends_on:
      - db

  glitch:
    image: fishnet/glitch:latest
    working_dir: /var/www
    env_file:
      - ./.env
    networks:
      - appnet

  online:
    image: fishnet/online:latest
    working_dir: /var/www
    volumes:
      - ./config/online/php.ini:/usr/local/etc/php/conf.d/settings.ini
      - ./config/online/Settings.php:/var/www/forum/Settings.php
      - ./data/online/cache/:/var/www/forum/cache/
    env_file:
      - ./.env
    networks:
      - appnet
    environment:
      DB_DATABASE: online
      MAINTENANCE_MODE: $MAINTENANCE_MODE
      MAINTENANCE_TITLE: $MAINTENANCE_TITLE
      MAINTENANCE_MESSAGE: $MAINTENANCE_MESSAGE
      SITE_NAME: $FORUM_NAME
      SITE_LANGUAGE: $FORUM_LANGUAGE
      SITE_URL: $FORUM_URL
      OUTGOING_EMAIL: noreply@wetfish.net
    depends_on:
      - db

  wiki:
    image: fishnet/wiki:latest
    working_dir: /var/www
    environment:
      DB_DATABASE: wiki
      SITE_URL: $WIKI_URL
      ALLOWED_EMBEDS: $WIKI_ALLOWED_EMBEDS
    volumes:
      - ./config/wiki/config.php:/var/www/src/config.php
      - ./config/wiki/php.ini:/usr/local/etc/php/conf.d/settings.ini
      - ./data/wiki/upload/:/var/www/upload/
      - ./data/wiki/upload/:/config/www/wiki/upload/
    env_file:
      - ./.env
    networks:
      - appnet
    depends_on:
      - db

  webserver:
    image: ghcr.io/linuxserver/swag
    env_file:
      - ./.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: $TIMEZONE
      URL: $MAIN_URL
      SUBDOMAINS: $SUBDOMAINS
      ONLY_SUBDOMAINS: $ONLY_SUBDOMAINS
      VALIDATION: http
      EMAIL: $EMAIL
      STAGING: $STAGING
      EXTRA_DOMAINS: $EXTRA_DOMAINS
      #CERTPROVIDER: zerossl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/config/nginx/site-confs
      - files:/config/www/static
      - ./data/wiki/upload/:/config/www/wiki/upload/
      - ./data/online/fish/:/config/www/online/forum/fish/
      - ./data/online/Themes/:/config/www/online/forum/Themes/
    networks:
      - appnet

  # MySQL Service
  db:
    image: mariadb
    command: --sql-mode=""
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: root
    volumes:
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./config/mysql.ini:/etc/mysql/conf.d/mysql.ini
      - ./dumps:/dumps
      - ./data/dbdata:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
    files:
      driver: local
