version: '3.6'
services:
  
  #webserver:
  #  image: ghcr.io/linuxserver/swag
  #  container_name: swag
  #  restart: unless-stopped
  #  environment:
  #    PUID: 1000
  #    PGID: 1000
  #    TZ: $TIMEZONE
  #    URL: $SITE_URL
  #    SUBDOMAINS: $SUBDOMAINS
  #    ONLY_SUBDOMAINS: $ONLY_SUBDOMAINS
  #    VALIDATION: http
  #    EMAIL: $EMAIL # optional
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./config/site-confs:/config/nginx/site-confs
  #    - ./config/fastcgi_params:/config/nginx/fastcgi_params
  #    - click:/var/www/click
  #    - danger:/var/www/danger
  #    - glitch:/var/www/glitch
  #    - files:/var/www/static
  #    - online:/var/www/online
  #    - wiki:/var/www/wiki
  #  networks:
  #    - app-network
  #  depends_on:
  #    - db

  # Temporary nginx config
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    networks: 
      - appnet
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - click:/var/www/click
      - danger:/var/www/danger
      - glitch:/var/www/glitch
      - files:/var/www/static
      - online:/var/www/forum
      - wiki:/var/www/wiki

networks:
  appnet:
    external:
      name: appnet

volumes:
    click:
      external: true
    danger:
      external: true
    glitch:
      external: true
    files:
      external: true
    online:
      external: true
    wiki:
      external: true
